export enum ChatErrorCode {
  // Auth
  AUTH_FAILED = 'CHAT_AUTH_FAILED',
  AUTH_TOKEN_INVALID = 'CHAT_AUTH_TOKEN_INVALID',
  AUTH_FORBIDDEN = 'CHAT_AUTH_FORBIDDEN',

  // Channel
  CHANNEL_NOT_FOUND = 'CHAT_CHANNEL_NOT_FOUND',
  CHANNEL_ALREADY_EXISTS = 'CHAT_CHANNEL_ALREADY_EXISTS',
  CHANNEL_FROZEN = 'CHAT_CHANNEL_FROZEN',
  CHANNEL_MEMBER_LIMIT = 'CHAT_CHANNEL_MEMBER_LIMIT',
  CHANNEL_PIN_LIMIT = 'CHAT_CHANNEL_PIN_LIMIT',

  // Member
  NOT_CHANNEL_MEMBER = 'CHAT_NOT_CHANNEL_MEMBER',
  NOT_CHANNEL_OPERATOR = 'CHAT_NOT_CHANNEL_OPERATOR',
  ALREADY_CHANNEL_MEMBER = 'CHAT_ALREADY_CHANNEL_MEMBER',
  USER_MUTED = 'CHAT_USER_MUTED',
  USER_BANNED = 'CHAT_USER_BANNED',

  // Message
  MESSAGE_NOT_FOUND = 'CHAT_MESSAGE_NOT_FOUND',
  MESSAGE_NOT_OWNER = 'CHAT_MESSAGE_NOT_OWNER',
  MESSAGE_TOO_LONG = 'CHAT_MESSAGE_TOO_LONG',

  // Poll
  POLL_NOT_FOUND = 'CHAT_POLL_NOT_FOUND',
  POLL_CLOSED = 'CHAT_POLL_CLOSED',
  POLL_OPTION_LIMIT = 'CHAT_POLL_OPTION_LIMIT',
  POLL_ALREADY_VOTED = 'CHAT_POLL_ALREADY_VOTED',

  // Scheduled
  SCHEDULED_NOT_FOUND = 'CHAT_SCHEDULED_NOT_FOUND',
  SCHEDULED_ALREADY_SENT = 'CHAT_SCHEDULED_ALREADY_SENT',
  SCHEDULED_INVALID_TIME = 'CHAT_SCHEDULED_INVALID_TIME',

  // User
  USER_NOT_FOUND = 'CHAT_USER_NOT_FOUND',
  USER_ALREADY_BLOCKED = 'CHAT_USER_ALREADY_BLOCKED',

  // Storage
  FILE_TOO_LARGE = 'CHAT_FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED = 'CHAT_FILE_TYPE_NOT_ALLOWED',
  UPLOAD_FAILED = 'CHAT_UPLOAD_FAILED',

  // Generic
  VALIDATION_ERROR = 'CHAT_VALIDATION_ERROR',
  CONFLICT = 'CHAT_CONFLICT',
  INTERNAL_ERROR = 'CHAT_INTERNAL_ERROR',
  RATE_LIMITED = 'CHAT_RATE_LIMITED',
}

export const ERROR_HTTP_STATUS: Record<string, number> = {
  // 400
  [ChatErrorCode.VALIDATION_ERROR]: 400,
  [ChatErrorCode.MESSAGE_TOO_LONG]: 400,
  [ChatErrorCode.POLL_OPTION_LIMIT]: 400,
  [ChatErrorCode.SCHEDULED_INVALID_TIME]: 400,
  [ChatErrorCode.FILE_TOO_LARGE]: 400,
  [ChatErrorCode.FILE_TYPE_NOT_ALLOWED]: 400,

  // 401
  [ChatErrorCode.AUTH_FAILED]: 401,
  [ChatErrorCode.AUTH_TOKEN_INVALID]: 401,

  // 403
  [ChatErrorCode.AUTH_FORBIDDEN]: 403,
  [ChatErrorCode.NOT_CHANNEL_MEMBER]: 403,
  [ChatErrorCode.NOT_CHANNEL_OPERATOR]: 403,
  [ChatErrorCode.USER_MUTED]: 403,
  [ChatErrorCode.USER_BANNED]: 403,
  [ChatErrorCode.CHANNEL_FROZEN]: 403,

  // 404
  [ChatErrorCode.CHANNEL_NOT_FOUND]: 404,
  [ChatErrorCode.MESSAGE_NOT_FOUND]: 404,
  [ChatErrorCode.POLL_NOT_FOUND]: 404,
  [ChatErrorCode.SCHEDULED_NOT_FOUND]: 404,
  [ChatErrorCode.USER_NOT_FOUND]: 404,

  // 409
  [ChatErrorCode.CHANNEL_ALREADY_EXISTS]: 409,
  [ChatErrorCode.ALREADY_CHANNEL_MEMBER]: 409,
  [ChatErrorCode.USER_ALREADY_BLOCKED]: 409,
  [ChatErrorCode.POLL_ALREADY_VOTED]: 409,
  [ChatErrorCode.CONFLICT]: 409,

  // 410
  [ChatErrorCode.POLL_CLOSED]: 410,
  [ChatErrorCode.SCHEDULED_ALREADY_SENT]: 410,

  // 413
  [ChatErrorCode.CHANNEL_MEMBER_LIMIT]: 413,
  [ChatErrorCode.CHANNEL_PIN_LIMIT]: 413,

  // 429
  [ChatErrorCode.RATE_LIMITED]: 429,

  // 500
  [ChatErrorCode.INTERNAL_ERROR]: 500,
  [ChatErrorCode.UPLOAD_FAILED]: 500,
};
