export const CHAT_USER_RESOLVER = Symbol('CHAT_USER_RESOLVER');
export const CHAT_AUTH_GUARD = Symbol('CHAT_AUTH_GUARD');
export const CHAT_USER_EXTRACTOR = Symbol('CHAT_USER_EXTRACTOR');
export const CHAT_STORAGE_PROVIDER = Symbol('CHAT_STORAGE_PROVIDER');
export const CHAT_EVENT_HANDLER = Symbol('CHAT_EVENT_HANDLER');
export const CHAT_MODULE_OPTIONS = Symbol('CHAT_MODULE_OPTIONS');
